import assert from 'node:assert/strict';
import { initializeAnalogScenarioEngine, runAnalogScenarioEngine } from '../js/scenarios/AnalogScenarioEngine.js';
const cells=Array.from({length:100},(_,i)=>({derived:{stp:i<10?2:0},surfaceParcelValidity:{score:.8},features:{boundaryRelative:i<10?{type:'dryline',side:'ahead'}:null}}));
const world={validHourUtc:18,evolution:{config:{setupType:'dryline_cyclone',narrative:'isolated_supercells'}},synopticObjects:{fronts:[{type:'dryline',velocityKph:{east:18,north:1}}]},stormEngine:{dominantModes:[{mode:'discrete supercell',count:6},{mode:'multicell',count:4}]},meteorologicalIntegrity:{overallScore:.9},forEachCell(fn){cells.forEach(fn);}};
const report=initializeAnalogScenarioEngine(world);
assert.equal(report.version,'2.71.0');
assert.equal(report.mode,'critic-not-driver');
assert.ok(report.plausibility>0&&report.plausibility<=1);
assert.ok(report.confidenceFactor>=.78&&report.confidenceFactor<=1);
assert.ok(cells.every(c=>c.analogScenarioSupport?.version==='2.71.0'));
const again=runAnalogScenarioEngine(world);
assert.equal(world.analogScenarioHistory.length,2);
assert.ok(again.elapsedMs<100);
console.log('2.71.0 analog scenario intelligence: PASS');
