import assert from 'node:assert/strict';
import fs from 'node:fs';
const synoptic=fs.readFileSync(new URL('../js/synoptic/SynopticObjectEngine.js',import.meta.url),'utf8');
const critic=fs.readFileSync(new URL('../js/verification/CalibrationCritic.js',import.meta.url),'utf8');
const outlook=fs.readFileSync(new URL('../js/forecast/OutlookCycleEngine.js',import.meta.url),'utf8');
assert.match(synoptic,/solveAtmosphericConstraints/);
assert.match(synoptic,/boundedVectorCorrection/);
assert.match(synoptic,/atmosphericConsistency/);
assert.match(synoptic,/objectConfidence/);
assert.match(synoptic,/applyAtmosphericConstraintTendencies/);
assert.match(synoptic,/sampleTriplePointSupport/);
assert.match(critic,/LOW_ATMOSPHERIC_CONSISTENCY/);
assert.match(critic,/meanFrontResidualErrorKm/);
assert.match(outlook,/synopticObjects\?\.triplePoint/);
console.log('2.54.0 atmospheric constraint solver regression: PASS');
