import assert from 'node:assert/strict';
import { applyForecastConfidence } from '../js/forecast/ForecastConfidenceEngine.js';
const width=8,height=8;
const grid=Array.from({length:64},()=>({tornadoProbability:15,hailProbability:30,windProbability:15,peakInitiation:.55,projectedStormOccupancy:.5,boundaryRelativePlacement:.6,ensembleForecast:{tornado:{occurrenceProbability:.32,conditionalHazardProbability:.8,spatialConcentration:.35,dominantClusterSupport:.2,weightedMemberFrequency:.3},hail:{occurrenceProbability:.5,conditionalHazardProbability:.8,spatialConcentration:.6,dominantClusterSupport:.5,weightedMemberFrequency:.55},wind:{occurrenceProbability:.4,conditionalHazardProbability:.6,spatialConcentration:.45,dominantClusterSupport:.35,weightedMemberFrequency:.4}},outlookAssimilation:{}}));
const memberProducts=Array.from({length:8},(_,index)=>({index,perturbation:{initiationFactor:1+(index-4)*.03},projection:{fields:{tornado:new Float64Array(64).fill(.02),hail:new Float64Array(64).fill(.04),wind:new Float64Array(64).fill(.03)},candidates:[{index,confidence:.6,lifetimeHours:3,corridor90RadiusCells:6,stateHistory:[{organization:.6,inflowQuality:.6,coldPoolStrength:.25}],finalState:{organization:.6,inflowQuality:.6,coldPoolStrength:.25}}]}}));
const report=applyForecastConfidence(grid,width,height,memberProducts,{key:'day1'});
assert.ok(['2.65.0','2.66.0'].includes(report.version));
assert.ok(grid[0].forecastConfidence.tornado.overallConfidence>0);
assert.ok(grid[0].tornadoProbability<=15,'confidence may contract but never inflate potential');
assert.ok(report.diagnostics.tornado.highTierSuppressedCells>0,'low confidence high tier should be suppressed');
console.log('2.65.0 forecast confidence engine: PASS');
