import assert from 'node:assert/strict';
import { buildForecastStormProjection } from '../js/forecast/ForecastStormProjectionEngine.js';
const width=8,height=8;
const grid=Array.from({length:width*height},(_,i)=>({peakInitiation:i===27?.8:.05,projectedStormOccupancy:i===27?.8:.05,hazardOverlapScore:i===27?1:.1,confidence:80,tornadoProbability:i===27?15:2,hailProbability:i===27?30:5,windProbability:5,conditionalTornadoIntensity:.8,conditionalHailIntensity:.9,conditionalWindIntensity:.3,boundaryRelativePlacement:.75,trajectory:{dxCells:4,dyCells:-2,mode:'discrete'},hazardTrajectories:{tornado:{dxCells:4,dyCells:-2},hail:{dxCells:4,dyCells:-2},wind:{dxCells:3,dyCells:0}}}));
const p=buildForecastStormProjection(grid,width,height,{key:'day1'});
assert.equal(p.version,'2.60.1');
assert.ok(p.candidates.length>0);
assert.ok(p.candidates[0].track.length>2);
assert.ok(Array.isArray(p.candidates[0].motionHistory));
assert.ok(Number.isFinite(p.candidates[0].corridor50RadiusCells));
assert.ok(Number.isFinite(p.candidates[0].corridor90RadiusCells));
console.log('2.60.1 forecast/realized storm intelligence integration: PASS');
