import assert from 'node:assert/strict';
import { Atmosphere } from '../js/atmosphere.js?v=2.17.0';
import { generateScenario } from '../js/scenarios/scenarioGenerator.js?v=2.17.0';
import { initializeEvolution, advanceAtmosphere } from '../js/evolution.js?v=2.17.0';
import { sampleRadarProduct, coverageAt, getRadarScanStatus, RADAR_SCAN_INTERVAL_HOURS } from '../js/radar/RadarNetwork.js?v=2.17.0';
const world=new Atmosphere(50,50); const config=generateScenario(world,11); initializeEvolution(world,config);
assert.equal(world.radarNetwork.stations.length,5);
assert.equal(RADAR_SCAN_INTERVAL_HOURS,5/60);
const first=world.radarNetwork.stations[0], initialScan=first.scanNumber;
advanceAtmosphere(world,.5);
assert.equal(first.scanNumber,initialScan+6,'A half-hour atmosphere step should contain six five-minute radar scans');
const scan=getRadarScanStatus(world,first.id);
assert.equal(scan.rangeKm,first.rangeKm); assert.ok(scan.nextScanHourUtc>scan.lastScanHourUtc);
const center={x:world.domainWidthKm/2,y:world.domainHeightKm/2}; assert.ok(coverageAt(world,center.x,center.y)>0);
world.storms=[{active:true,id:'TEST',positionKm:center,velocityKph:{east:50,north:15},intensity:.9,organization:.9,rotationStrength:.8,orientationDeg:70,radar:{radiusXKm:25,radiusYKm:14},hazards:{tornadoProbability:.7,hailProbability:.6}}];
const z=sampleRadarProduct(world,center.x,center.y,'reflectivity'),v=sampleRadarProduct(world,center.x+5,center.y+5,'velocity'),cc=sampleRadarProduct(world,center.x,center.y,'correlationCoefficient');
assert.ok(z.covered&&z.value>45,`weak reflectivity ${z.value}`);assert.ok(Number.isFinite(v.value));assert.ok(cc.value<.9,`CC did not respond ${cc.value}`);
let holes=0;for(let y=0;y<world.domainHeightKm;y+=10)for(let x=0;x<world.domainWidthKm;x+=10)if(coverageAt(world,x,y)<.04)holes++;assert.ok(holes>0,'Expected radar holes');
console.log(JSON.stringify({stations:5,scanNumber:first.scanNumber,scanIntervalMinutes:5,z:z.value,v:v.value,cc:cc.value,holes},null,2));
