import assert from 'node:assert/strict';
import { Atmosphere } from '../js/atmosphere.js';
import { generateScenario } from '../js/scenarios/scenarioGenerator.js';
import { initializeEvolution, advanceAtmosphere } from '../js/evolution.js';

const world = new Atmosphere(50,50);
const config = generateScenario(world, 'synoptic-evolution-test-251');
initializeEvolution(world, config);
const initial = structuredClone(world.synopticObjects);
assert.equal(initial.version, 2);
assert.ok(initial.convectiveBudget.rechargeContext);
assert.ok(initial.environmentalTendencies);
advanceAtmosphere(world, 6, { advanceStorms:false });
const evolved = world.synopticObjects;
assert.ok(evolved.surfaceLow.lifecycleProgress > initial.surfaceLow.lifecycleProgress);
assert.notDeepEqual(evolved.surfaceLow.positionKm, initial.surfaceLow.positionKm);
assert.ok(Number.isFinite(evolved.convectiveBudget.rechargeRate));
assert.ok(evolved.convectiveBudget.rechargeRate <= 0.62);
assert.ok(evolved.convectiveMemory);
console.log('2.51.0 synoptic evolution engine regression: PASS');
