// Generated by scripts/fit-outlook-calibration.mjs from outlook-audit runs (tiers: calibration
// off; categories: tiers on, categories off). Maps published tier -> verified tier per day and
// hazard, and issued category -> verified category per day. Do not hand-edit.
export const OUTLOOK_CALIBRATION_TABLE = {
  "version": "fitted-2026-10-09",
  "fittedFrom": {
    "seeds": [
      1,
      11,
      23,
      42,
      99,
      2011,
      2013,
      20240506
    ],
    "hours": 72,
    "minCellsPerTier": 300
  },
  "tiers": {
    "day1": {
      "tornado": {
        "2": 10,
        "5": 15,
        "10": 30,
        "15": 45
      },
      "hail": {
        "5": 30,
        "15": 30,
        "30": 45,
        "45": 60
      },
      "wind": {
        "5": 30,
        "15": 60
      }
    },
    "day2": {
      "tornado": {
        "2": 15,
        "5": 60
      },
      "hail": {
        "5": 15,
        "15": 15
      },
      "wind": {
        "5": 30
      }
    },
    "day3": {
      "tornado": {
        "2": 15
      },
      "hail": {
        "5": 30,
        "15": 30
      },
      "wind": {
        "5": 30
      }
    }
  },
  "categoriesFittedFrom": {
    "seeds": [
      1,
      11,
      23,
      42,
      99,
      2011,
      2013,
      20240506
    ],
    "hours": 72,
    "minProductsPerCategory": 4
  },
  "categories": {
    "day1": {
      "HIGH": "MDT"
    },
    "day2": {
      "ENH": "MDT",
      "HIGH": "MDT"
    },
    "day3": {
      "ENH": "MDT"
    }
  }
};
